-- ============================================================================
-- SoccerSmartBet PostgreSQL Schema
-- ============================================================================
-- Version: 1.0
-- Date: 2025-11-21
-- Purpose: Complete database schema for AI soccer betting system
--
-- Key Design Principles:
-- 1. Relational integrity with foreign keys
-- 2. Performance-optimized indexes for frequent queries
-- 3. Parallel write support for agent-generated reports
-- 4. Timestamps for historical tracking
-- 5. Data validation via check constraints
-- ============================================================================

-- Enable UUID extension for unique identifiers
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLE: teams
-- Purpose: Master data for football teams
-- Data Sources: football-data.org, API-Football
-- ============================================================================
CREATE TABLE teams (
    team_id SERIAL PRIMARY KEY,
    -- External API identifiers
    external_id VARCHAR(100),
    external_source VARCHAR(50), -- 'football-data', 'api-football', etc.
    
    -- Team identification
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(100),
    
    -- League/competition information
    league VARCHAR(100),
    
    -- Venue information
    venue VARCHAR(255),
    city VARCHAR(100),
    country VARCHAR(100),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_external_team UNIQUE (external_id, external_source)
);

-- Indexes for teams
CREATE INDEX idx_teams_name ON teams(name);
CREATE INDEX idx_teams_league ON teams(league);
CREATE INDEX idx_teams_external ON teams(external_id, external_source);

COMMENT ON TABLE teams IS 'Master data for football teams from various data sources';
COMMENT ON COLUMN teams.external_id IS 'Team ID from external API (e.g., 33 from API-Football)';
COMMENT ON COLUMN teams.external_source IS 'Source API name for tracking data origin';

-- ============================================================================
-- TABLE: players
-- Purpose: Player roster for injury/suspension tracking
-- Data Sources: API-Football sidelined endpoint, football-data.org
-- ============================================================================
CREATE TABLE players (
    player_id SERIAL PRIMARY KEY,
    -- External API identifiers
    external_id VARCHAR(100),
    external_source VARCHAR(50),
    
    -- Player details
    team_id INTEGER NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    position VARCHAR(50), -- 'Goalkeeper', 'Defender', 'Midfielder', 'Forward'
    
    -- Importance flag (for injury impact analysis)
    is_key_player BOOLEAN DEFAULT FALSE,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_external_player UNIQUE (external_id, external_source)
);

-- Indexes for players
CREATE INDEX idx_players_team ON players(team_id);
CREATE INDEX idx_players_name ON players(name);
CREATE INDEX idx_players_key ON players(is_key_player) WHERE is_key_player = TRUE;

COMMENT ON TABLE players IS 'Player roster for tracking injuries, suspensions, and key player status';
COMMENT ON COLUMN players.is_key_player IS 'Flag indicating if player is critical for team performance';

-- ============================================================================
-- TABLE: games
-- Purpose: Daily match fixtures and their processing status
-- Data Sources: football-data.org, API-Football
-- ============================================================================
CREATE TABLE games (
    game_id SERIAL PRIMARY KEY,
    -- External API identifiers
    external_id VARCHAR(100),
    external_source VARCHAR(50),
    
    -- Match scheduling
    match_date DATE NOT NULL,
    kickoff_time TIME NOT NULL,
    timezone VARCHAR(50) DEFAULT 'UTC',
    
    -- Teams
    home_team_id INTEGER NOT NULL REFERENCES teams(team_id) ON DELETE RESTRICT,
    away_team_id INTEGER NOT NULL REFERENCES teams(team_id) ON DELETE RESTRICT,
    
    -- Competition information
    league VARCHAR(100) NOT NULL,
    competition VARCHAR(255), -- 'Premier League', 'Champions League', etc.
    
    -- Venue
    venue VARCHAR(255),
    
    -- Processing status for Pre-Gambling Flow
    status VARCHAR(50) DEFAULT 'pending',
    -- Status values:
    --   'pending': Initial state after Smart Game Picker selection
    --   'selected': Passed odds filter from winner.co.il
    --   'filtered': Did not meet minimum odds threshold
    --   'processing': Reports being generated by agents
    --   'ready_for_betting': Reports completed, ready for Gambling Flow
    --   'betting_open': User/AI can place bets
    --   'betting_closed': Deadline passed
    --   'in_progress': Match started
    --   'completed': Match finished, results available
    --   'cancelled': Match cancelled (weather, etc.)
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_external_game UNIQUE (external_id, external_source),
    CONSTRAINT different_teams CHECK (home_team_id != away_team_id),
    CONSTRAINT valid_status CHECK (status IN (
        'pending', 'selected', 'filtered', 'processing', 
        'ready_for_betting', 'betting_open', 'betting_closed', 
        'in_progress', 'completed', 'cancelled'
    ))
);

-- Indexes for games (critical for performance)
CREATE INDEX idx_games_date ON games(match_date);
CREATE INDEX idx_games_status ON games(status);
CREATE INDEX idx_games_home_team ON games(home_team_id);
CREATE INDEX idx_games_away_team ON games(away_team_id);
CREATE INDEX idx_games_league ON games(league);
CREATE INDEX idx_games_date_status ON games(match_date, status); -- Composite for daily queries
CREATE INDEX idx_games_external ON games(external_id, external_source);

COMMENT ON TABLE games IS 'Daily match fixtures with processing status tracking';
COMMENT ON COLUMN games.status IS 'Tracks game through Pre-Gambling → Gambling → Post-Games flows';

-- ============================================================================
-- TABLE: betting_lines
-- Purpose: Odds data from winner.co.il (Israeli Toto)
-- Data Source: winner.co.il (web scraping)
-- ============================================================================
CREATE TABLE betting_lines (
    line_id SERIAL PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    
    -- Israeli Toto odds (3-way)
    n1 DECIMAL(5, 2) NOT NULL, -- Home win odds
    n2 DECIMAL(5, 2) NOT NULL, -- Away win odds
    n3 DECIMAL(5, 2) NOT NULL, -- Draw odds (nx)
    
    -- Data source tracking
    source VARCHAR(100) DEFAULT 'winner.co.il',
    fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT positive_odds_n1 CHECK (n1 > 1.0),
    CONSTRAINT positive_odds_n2 CHECK (n2 > 1.0),
    CONSTRAINT positive_odds_n3 CHECK (n3 > 1.0)
);

-- Indexes for betting_lines
CREATE INDEX idx_betting_lines_game ON betting_lines(game_id);
CREATE INDEX idx_betting_lines_fetched ON betting_lines(fetched_at DESC);

COMMENT ON TABLE betting_lines IS 'Betting odds from winner.co.il (Israeli Toto) - n1 (home), n2 (away), n3 (draw)';
COMMENT ON COLUMN betting_lines.n1 IS 'Home win odds (e.g., 2.10 means 100 NIS bet returns 210 NIS if home wins)';
COMMENT ON COLUMN betting_lines.n2 IS 'Away win odds';
COMMENT ON COLUMN betting_lines.n3 IS 'Draw odds';

-- ============================================================================
-- TABLE: game_reports
-- Purpose: AI-generated game analysis from Game Intelligence Agent
-- Data Sources: API-Football H2H, venue data, weather, news scraping
-- ============================================================================
CREATE TABLE game_reports (
    report_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id INTEGER NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    
    -- AI-generated analysis sections
    h2h_insights TEXT, -- Head-to-head pattern analysis
    atmosphere_summary TEXT, -- Fan sentiment, crowd factors
    weather_risk TEXT, -- Cancellation risk, draw probability impact
    venue_factors TEXT, -- Home advantage, crowd size/hostility
    
    -- Data quality tracking
    data_quality JSONB, -- {"h2h": "complete", "weather": "partial", "news": "missing"}
    
    -- Agent metadata
    agent_version VARCHAR(50), -- Track which agent version generated report
    llm_model VARCHAR(100), -- e.g., 'gpt-4o-mini'
    processing_time_seconds DECIMAL(10, 2),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_game_report UNIQUE (game_id)
);

-- Indexes for game_reports
CREATE INDEX idx_game_reports_game ON game_reports(game_id);
CREATE INDEX idx_game_reports_created ON game_reports(created_at DESC);
CREATE INDEX idx_game_reports_quality ON game_reports USING GIN (data_quality);

COMMENT ON TABLE game_reports IS 'AI-generated game analysis from Game Intelligence Agent with tool-based data fetching';
COMMENT ON COLUMN game_reports.h2h_insights IS 'AI analysis of head-to-head patterns (not raw stats)';
COMMENT ON COLUMN game_reports.data_quality IS 'JSON tracking completeness of each data category';

-- ============================================================================
-- TABLE: team_reports
-- Purpose: AI-generated team analysis from Team Intelligence Agent
-- Data Sources: API-Football (form, injuries, suspensions), news scraping
-- ============================================================================
CREATE TABLE team_reports (
    report_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id INTEGER NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
    
    -- Team readiness metrics
    recovery_days INTEGER, -- Days since last match
    
    -- AI-generated analysis sections
    form_trend TEXT, -- "improving", "declining", "stable" with AI reasoning
    injury_impact TEXT, -- Assessment: "critical starters missing" vs "minor depth issues"
    rotation_risk TEXT, -- Prediction based on upcoming fixtures
    key_players_status TEXT, -- Form assessment of top performers
    morale_stability TEXT, -- Sentiment from news (coach pressure, controversies)
    preparation_quality TEXT, -- Training/prep signals from news
    relevant_news TEXT, -- Betting-relevant news only (AI-filtered)
    
    -- Data quality tracking
    data_quality JSONB, -- {"form": "complete", "injuries": "complete", "news": "partial"}
    
    -- Agent metadata
    agent_version VARCHAR(50),
    llm_model VARCHAR(100),
    processing_time_seconds DECIMAL(10, 2),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_team_game_report UNIQUE (game_id, team_id),
    CONSTRAINT valid_recovery_days CHECK (recovery_days >= 0)
);

-- Indexes for team_reports
CREATE INDEX idx_team_reports_game ON team_reports(game_id);
CREATE INDEX idx_team_reports_team ON team_reports(team_id);
CREATE INDEX idx_team_reports_game_team ON team_reports(game_id, team_id); -- Composite for lookups
CREATE INDEX idx_team_reports_created ON team_reports(created_at DESC);
CREATE INDEX idx_team_reports_quality ON team_reports USING GIN (data_quality);

COMMENT ON TABLE team_reports IS 'AI-generated team analysis from Team Intelligence Agent - 2 reports per game (home + away)';
COMMENT ON COLUMN team_reports.recovery_days IS 'Calculated days since teams last match (affects fatigue)';
COMMENT ON COLUMN team_reports.injury_impact IS 'Critical: AI must identify if injured players are starters vs bench warmers';

-- ============================================================================
-- TABLE: unfiltered_games
-- Purpose: Snapshot of ALL games considered by Smart Game Picker (even rejected)
-- Purpose: Historical analysis of filtering decisions
-- ============================================================================
CREATE TABLE unfiltered_games (
    snapshot_id SERIAL PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    
    -- Full game data as JSON (flexible schema)
    game_data JSONB NOT NULL,
    
    -- Filtering decision
    was_selected BOOLEAN DEFAULT FALSE,
    filter_reason TEXT, -- Why excluded: "low_odds", "uninteresting_matchup", "minor_league"
    
    -- Smart Game Picker reasoning (AI justification)
    picker_reasoning TEXT,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for unfiltered_games
CREATE INDEX idx_unfiltered_games_date ON unfiltered_games(snapshot_date);
CREATE INDEX idx_unfiltered_games_selected ON unfiltered_games(was_selected);
CREATE INDEX idx_unfiltered_games_data ON unfiltered_games USING GIN (game_data);

COMMENT ON TABLE unfiltered_games IS 'Historical snapshot of all games considered, including rejected ones';
COMMENT ON COLUMN unfiltered_games.game_data IS 'Full fixture data from API as JSONB for flexibility';

-- ============================================================================
-- TABLE: bets
-- Purpose: User and AI betting predictions (single bets per game)
-- ============================================================================
CREATE TABLE bets (
    bet_id SERIAL PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    
    -- Bettor identification
    bettor VARCHAR(10) NOT NULL, -- 'user' or 'ai'
    
    -- Bet details
    prediction VARCHAR(5) NOT NULL, -- '1' (home), 'x' (draw), '2' (away)
    odds DECIMAL(5, 2) NOT NULL, -- Odds at time of bet placement
    stake DECIMAL(10, 2) NOT NULL DEFAULT 100.00, -- Always 100 NIS per rules
    
    -- AI justification (for AI bets only)
    justification TEXT,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT valid_bettor CHECK (bettor IN ('user', 'ai')),
    CONSTRAINT valid_prediction CHECK (prediction IN ('1', 'x', '2')),
    CONSTRAINT positive_odds CHECK (odds > 1.0),
    CONSTRAINT fixed_stake CHECK (stake = 100.00),
    CONSTRAINT unique_bet_per_game UNIQUE (game_id, bettor)
);

-- Indexes for bets
CREATE INDEX idx_bets_game ON bets(game_id);
CREATE INDEX idx_bets_bettor ON bets(bettor);
CREATE INDEX idx_bets_created ON bets(created_at DESC);

COMMENT ON TABLE bets IS 'User and AI betting predictions - single bets only, 100 NIS stake per game';
COMMENT ON COLUMN bets.stake IS 'Always 100 NIS per system rules (non-monetary simulation)';
COMMENT ON COLUMN bets.justification IS 'AI reasoning for bet selection (empty for user bets)';

-- ============================================================================
-- TABLE: results
-- Purpose: Match results and P&L calculations
-- ============================================================================
CREATE TABLE results (
    result_id SERIAL PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    
    -- Match outcome
    outcome VARCHAR(5) NOT NULL, -- '1' (home win), 'x' (draw), '2' (away win)
    home_score INTEGER NOT NULL,
    away_score INTEGER NOT NULL,
    
    -- Bet references
    user_bet_id INTEGER REFERENCES bets(bet_id) ON DELETE SET NULL,
    ai_bet_id INTEGER REFERENCES bets(bet_id) ON DELETE SET NULL,
    
    -- P&L calculations (profit/loss in NIS)
    user_pnl DECIMAL(10, 2), -- Positive = profit, Negative = loss
    ai_pnl DECIMAL(10, 2),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT valid_outcome CHECK (outcome IN ('1', 'x', '2')),
    CONSTRAINT valid_scores CHECK (home_score >= 0 AND away_score >= 0),
    CONSTRAINT unique_game_result UNIQUE (game_id)
);

-- Indexes for results
CREATE INDEX idx_results_game ON results(game_id);
CREATE INDEX idx_results_outcome ON results(outcome);
CREATE INDEX idx_results_created ON results(created_at DESC);

COMMENT ON TABLE results IS 'Match results and profit/loss calculations for both user and AI';
COMMENT ON COLUMN results.user_pnl IS 'User profit/loss: win = stake × odds - stake, loss = -stake';
COMMENT ON COLUMN results.ai_pnl IS 'AI profit/loss: win = stake × odds - stake, loss = -stake';

-- ============================================================================
-- TRIGGERS: Auto-update updated_at timestamps
-- ============================================================================

-- Function to update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for tables with updated_at
CREATE TRIGGER update_teams_updated_at
    BEFORE UPDATE ON teams
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_players_updated_at
    BEFORE UPDATE ON players
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_games_updated_at
    BEFORE UPDATE ON games
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_betting_lines_updated_at
    BEFORE UPDATE ON betting_lines
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON FUNCTION update_updated_at_column() IS 'Auto-updates updated_at timestamp on row modification';

-- ============================================================================
-- VIEWS: Useful pre-joined queries for common operations
-- ============================================================================

-- View: Active games ready for betting with reports
CREATE VIEW games_ready_for_betting AS
SELECT 
    g.game_id,
    g.match_date,
    g.kickoff_time,
    ht.name AS home_team,
    at.name AS away_team,
    g.league,
    g.competition,
    bl.n1,
    bl.n2,
    bl.n3,
    gr.report_id AS game_report_id,
    EXISTS(SELECT 1 FROM team_reports WHERE game_id = g.game_id) AS has_team_reports
FROM games g
JOIN teams ht ON g.home_team_id = ht.team_id
JOIN teams at ON g.away_team_id = at.team_id
LEFT JOIN betting_lines bl ON g.game_id = bl.game_id
LEFT JOIN game_reports gr ON g.game_id = gr.game_id
WHERE g.status = 'ready_for_betting';

COMMENT ON VIEW games_ready_for_betting IS 'Games with completed reports ready for user/AI betting';

-- View: Daily P&L summary
CREATE VIEW daily_pnl_summary AS
SELECT 
    g.match_date,
    COUNT(r.result_id) AS games_count,
    SUM(r.user_pnl) AS user_total_pnl,
    SUM(r.ai_pnl) AS ai_total_pnl,
    AVG(r.user_pnl) AS user_avg_pnl,
    AVG(r.ai_pnl) AS ai_avg_pnl,
    SUM(CASE WHEN r.user_pnl > 0 THEN 1 ELSE 0 END) AS user_wins,
    SUM(CASE WHEN r.ai_pnl > 0 THEN 1 ELSE 0 END) AS ai_wins
FROM results r
JOIN games g ON r.game_id = g.game_id
GROUP BY g.match_date
ORDER BY g.match_date DESC;

COMMENT ON VIEW daily_pnl_summary IS 'Daily profit/loss summary for analytics';

-- ============================================================================
-- INDEXES: Additional performance optimization
-- ============================================================================

-- GIN index for JSONB data quality search
CREATE INDEX idx_game_reports_data_quality_keys ON game_reports ((data_quality -> 'h2h'));
CREATE INDEX idx_team_reports_data_quality_keys ON team_reports ((data_quality -> 'injuries'));

-- Partial indexes for active games (most queried)
CREATE INDEX idx_games_active ON games(game_id, status) 
    WHERE status IN ('pending', 'selected', 'processing', 'ready_for_betting', 'betting_open');

-- ============================================================================
-- GRANTS: Set up permissions (adjust based on application roles)
-- ============================================================================

-- Example: Create application role (uncomment for production)
-- CREATE ROLE soccersmartbet_app WITH LOGIN PASSWORD 'secure_password_here';
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO soccersmartbet_app;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO soccersmartbet_app;

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================

-- Schema version tracking
CREATE TABLE schema_version (
    version VARCHAR(20) PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

INSERT INTO schema_version (version, description) 
VALUES ('1.0', 'Initial schema with 9 core tables, indexes, and triggers');

COMMENT ON TABLE schema_version IS 'Tracks database schema versions for migration management';
